<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="Data">
    <PackageVersion Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup Label="Analyzers">
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup Label="Logging">
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup Label="Packaging">
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.assert" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

</Project>
